<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerZe4EzVn\srcDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerZe4EzVn/srcDevDebugProjectContainer.php';
}

if (!class_exists(srcDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerZe4EzVn\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZe4EzVn\srcDevDebugProjectContainer();
